"""add_refund_requests

Revision ID: 48e68e0d1260
Revises: e2b10a5bcf41
Create Date: 2026-06-23 10:46:35.285350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e68e0d1260'
down_revision: Union[str, None] = 'e2b10a5bcf41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BotOwnerRefundRequest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['BotOwner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('BotBooking', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'CONFIRMED'::character varying"))
    op.add_column('BotOwner', sa.Column('subscriptionStartedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BotOwner', 'subscriptionStartedAt')
    op.alter_column('BotBooking', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'CONFIRMED'::character varying"))
    op.drop_table('BotOwnerRefundRequest')
    # ### end Alembic commands ###
