"""add_reminder_columns

Revision ID: 961d0ec5bd76
Revises: 55b869ee54ae
Create Date: 2026-06-21 18:25:42.450207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '961d0ec5bd76'
down_revision: Union[str, None] = '55b869ee54ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BotBooking', sa.Column('reminderSent', sa.Boolean(), nullable=True))
    op.alter_column('BotBooking', 'teamName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotBooking', 'captainName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotBooking', 'captainPhone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotBooking', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('BotBooking_slotId_fkey', 'BotBooking', type_='foreignkey')
    op.create_foreign_key(None, 'BotBooking', 'BotTurfSlot', ['slotId'], ['id'])
    op.drop_column('BotBooking', 'amountPaid')
    op.drop_column('BotBooking', 'paymentId')
    op.alter_column('BotJoinRequest', 'playerName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotJoinRequest', 'playerPhone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotJoinRequest', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotJoinRequest', 'joiningAmount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('BotJoinRequest', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('BotJoinRequest_bookingId_fkey', 'BotJoinRequest', type_='foreignkey')
    op.create_foreign_key(None, 'BotJoinRequest', 'BotBooking', ['bookingId'], ['id'])
    op.add_column('BotOwner', sa.Column('churnReminderSentAt', sa.DateTime(), nullable=True))
    op.alter_column('BotOwner', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotOwner', 'mobile',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotOwner', 'turfName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotOwner', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotOwner', 'photoUrls',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotOwner', 'gst',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'msme',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'msmeCardUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'utilityBillUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'upiId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'razorpayContactId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'razorpayFundAccountId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('BotOwner', 'businessPhone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'subscriptionActive',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('BotOwner', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('BotOwner', 'openingTime',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'06:00 AM'::text"))
    op.alter_column('BotOwner', 'closingTime',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'10:00 PM'::text"))
    op.drop_index('BotOwner_businessPhone_key', table_name='BotOwner')
    op.drop_index('BotOwner_mobile_key', table_name='BotOwner')
    op.create_unique_constraint(None, 'BotOwner', ['mobile'])
    op.create_unique_constraint(None, 'BotOwner', ['businessPhone'])
    op.drop_column('BotOwner', 'pricePerHour')
    op.alter_column('BotSession', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotSession', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotSession', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotSession', 'context',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('BotSession', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True)
    op.drop_index('BotSession_phone_key', table_name='BotSession')
    op.create_unique_constraint(None, 'BotSession', ['phone'])
    op.alter_column('BotTurfSlot', 'date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotTurfSlot', 'timeSlot',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotTurfSlot', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('BotTurfSlot', 'blockedByOwner',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('BotTurfSlot', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('BotTurfSlot_ownerId_date_timeSlot_key', table_name='BotTurfSlot')
    op.create_unique_constraint('uq_owner_date_timeslot', 'BotTurfSlot', ['ownerId', 'date', 'timeSlot'])
    op.drop_constraint('BotTurfSlot_ownerId_fkey', 'BotTurfSlot', type_='foreignkey')
    op.create_foreign_key(None, 'BotTurfSlot', 'BotOwner', ['ownerId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'BotTurfSlot', type_='foreignkey')
    op.create_foreign_key('BotTurfSlot_ownerId_fkey', 'BotTurfSlot', 'BotOwner', ['ownerId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint('uq_owner_date_timeslot', 'BotTurfSlot', type_='unique')
    op.create_index('BotTurfSlot_ownerId_date_timeSlot_key', 'BotTurfSlot', ['ownerId', 'date', 'timeSlot'], unique=True)
    op.alter_column('BotTurfSlot', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('BotTurfSlot', 'blockedByOwner',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('BotTurfSlot', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotTurfSlot', 'timeSlot',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotTurfSlot', 'date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'BotSession', type_='unique')
    op.create_index('BotSession_phone_key', 'BotSession', ['phone'], unique=True)
    op.alter_column('BotSession', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False)
    op.alter_column('BotSession', 'context',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BotSession', 'state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotSession', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotSession', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('BotOwner', sa.Column('pricePerHour', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1000.0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'BotOwner', type_='unique')
    op.drop_constraint(None, 'BotOwner', type_='unique')
    op.create_index('BotOwner_mobile_key', 'BotOwner', ['mobile'], unique=True)
    op.create_index('BotOwner_businessPhone_key', 'BotOwner', ['businessPhone'], unique=True)
    op.alter_column('BotOwner', 'closingTime',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'10:00 PM'::text"))
    op.alter_column('BotOwner', 'openingTime',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'06:00 AM'::text"))
    op.alter_column('BotOwner', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('BotOwner', 'subscriptionActive',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('BotOwner', 'businessPhone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('BotOwner', 'razorpayFundAccountId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'razorpayContactId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'upiId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'utilityBillUrl',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'msmeCardUrl',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'msme',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'gst',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BotOwner', 'photoUrls',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotOwner', 'location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotOwner', 'turfName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotOwner', 'mobile',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotOwner', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('BotOwner', 'churnReminderSentAt')
    op.drop_constraint(None, 'BotJoinRequest', type_='foreignkey')
    op.create_foreign_key('BotJoinRequest_bookingId_fkey', 'BotJoinRequest', 'BotBooking', ['bookingId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('BotJoinRequest', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('BotJoinRequest', 'joiningAmount',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('BotJoinRequest', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotJoinRequest', 'playerPhone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotJoinRequest', 'playerName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('BotBooking', sa.Column('paymentId', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('BotBooking', sa.Column('amountPaid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'BotBooking', type_='foreignkey')
    op.create_foreign_key('BotBooking_slotId_fkey', 'BotBooking', 'BotTurfSlot', ['slotId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('BotBooking', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('BotBooking', 'captainPhone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotBooking', 'captainName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('BotBooking', 'teamName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('BotBooking', 'reminderSent')
    # ### end Alembic commands ###
